-- Génération automatique des checklists toiture pour 10 missions
-- Mission 6: Hangar Bernard MAGE (CADENET)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (6, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 8: Hangar Karl Biteau (EDOUARD)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (8, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 12: HANGAR Christian MIGNARD (DIAGPV)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (12, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 17: Hangar Renaud Sonnard (EDOUARD)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (17, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 18: Hangar Fabrice COMBY (ARTEMIS)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (18, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 21: HANGAR Benoit BERTELOOT (ARTEMIS)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (21, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 38: Hangar LAMIOT (ARTEMIS)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (38, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 39: VIEL (EDOUARD)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (39, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 43: Bourgeois (EDOUARD)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (43, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');

-- Mission 47: GFA LASCOMBES - ANTOINE MICOULEAU (DIAGPV)
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 1, 'Démontage/remontage ~25 panneaux pertinents', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Démontage d''au moins 25 panneaux pertinents (1er et dernier panneau d''une chaîne, etc.). Remontage sans atteinte à l''intégrité des panneaux ou de leurs supports. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 2, 'Conformité DTU 40.35', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la conformité aux règles du DTU 40.35 (couvertures par éléments métalliques en feuilles et longues feuilles en zinc). (Ref: DTU 40.35)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 3, 'Qualité montage/serrage SI sur support', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des Structures d''Intégration (SI) sur leur support. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 4, 'Qualité montage/serrage panneaux sur SI', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité et conformité du montage et serrage des panneaux photovoltaïques sur les structures d''intégration. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 5, 'Fixation cheminement câbles (supports, étanchéité)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la fixation du cheminement des câbles : pertinence des supports de fixation, maintien de l''étanchéité toiture, absence de percement non maîtrisé. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 6, 'Compatibilité/serrage/étanchéité connecteurs MC4', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle des raccordements : compatibilité des connecteurs mâle/femelle (type PVZH202B), serrages corrects, étanchéité assurée, protection contre ruissellement. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 7, 'Qualité cheminement câbles DC dans chemins de câbles', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement des câbles DC dans les chemins de câbles : fixation adéquate, rayons de courbure respectés, absence de contraintes mécaniques. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 8, 'Cheminement câbles (pas directement sur couverture)', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification que les câbles ne cheminent PAS directement sur la couverture. Utilisation obligatoire de supports adaptés. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 9, 'Raccordements terres', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la qualité du cheminement et du raccordement des terres : continuité électrique, serrage des connexions, utilisation de cosses adaptées. (Ref: CDC Girasole page 8)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 10, 'Étiquettes réglementaires tension DC', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Présence et conformité des étiquettes réglementaires indiquant la présence de tension DC dangereuse. (Ref: CDC Girasole page 8 + Réglementation)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 11, 'Respect notices montage / Interdiction marcher sur panneaux', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification du respect des notices de montage des panneaux. Contrôle visuel qu''aucune trace de passage sur panneaux n''est visible. INTERDICTION ABSOLUE de marcher sur les panneaux pendant l''audit. (Ref: CDC Girasole §2.2)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 12, 'Présence de film anticondensation ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Vérification de la présence et de l''état du film anticondensation sous la toiture (pare-vapeur). Contrôle de son intégrité, de son étanchéité et de sa continuité. (Ref: DTU 40.35 + CDC Girasole)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 13, 'Présence de limaille sous les modules liées au perçage du bac acier pour les supports ? ou points de rouille ou piquage visible ?', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Contrôle de la présence de limaille métallique sous les panneaux (résidus de perçage du bac acier). Vérification de l''absence de points de rouille, de corrosion ou de piquage visible sur la couverture métallique. Ces défauts peuvent compromettre l''étanchéité et la durabilité de la toiture. (Ref: DTU 40.35 + Prévention corrosion)');
INSERT INTO checklist_items_toiture (ordre_mission_id, item_numero, libelle, categorie, statut, commentaire) VALUES (47, 14, 'Mesurer la distance Modules > Rives / Modules > Faitage', 'AUDIT_TOITURE', 'NON_VERIFIE', 'Mesure des distances de sécurité entre les modules photovoltaïques et les éléments de toiture : distance modules-rives (bords latéraux de la toiture) et distance modules-faîtage (ligne de crête). Ces distances doivent respecter les normes DTU pour garantir l''étanchéité, la ventilation et la sécurité en cas d''intervention. Mesures en mètres ou centimètres à relever sur site. (Ref: DTU 40.35 + Règles sécurité incendie)');
